-- AlterTable
ALTER TABLE `user` ADD COLUMN `maxCharsAllTime` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `maxCharsMonth` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `maxCharsWeek` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `totalPosts` INTEGER NOT NULL DEFAULT 0;
